@startuml Canvas App And Power BI Dashboard - Context
title Power Platform Canvas App and Power BI report connected to internal API

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define EDSICONS https://raw.githubusercontent.com/equinor/design-system/develop/assets/icons/system-icons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define edsIconKey img:EDSICONS/security/key.svg
!define edsIconVerifiedUser img:EDSICONS/security/verified_user.svg
!define edsIconBadge img:EDSICONS/people/badge.svg

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include FONTAWESOME/users.puml

Person(user, "Users", "Users in need of functionality", $sprite="users")
Container(powerplatformapp, "Application", "Software system", "Power Platform solution")
Container_Ext(api, "API", "Software system", "Backend software systems")
System_Boundary(onprem, "On-premises"){
    Container_Ext(sap, "SAP", "Software system", "On-prem business data and management")
}

Rel(user, powerplatformapp, "Uses", "Equinor | AAD")
Rel(powerplatformapp, api, "Requests", "user_impersonation scope")
Rel(user, sap, "Uses on-premises", "RBAC")
Rel(api, sap, "Reads and writes data with user roles", "RBAC")


SHOW_FLOATING_LEGEND()
Lay_Distance(LEGEND(), powerplatformapp, 0)
@enduml