@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define EDSICONS https://raw.githubusercontent.com/equinor/design-system/develop/assets/icons/system-icons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define edsIconKey img:EDSICONS/security/key.svg
!define edsIconVerifiedUser img:EDSICONS/security/verified_user.svg
!define edsIconBadge img:EDSICONS/people/badge.svg

!include FONTAWESOME/users.puml

Person(user, "Users", "Users in need of functionality", $sprite="users")
Container(spa, "Application", "PowerApps", "Primary front end application")
Container_Ext(api, "API", "", "Specific business logic and data")
ContainerDb_Ext(db, "Database", "OMNIA", "Business data")
ContainerDb_Ext(db2, "Database", "Generic", "Business data")
Container_Ext(sap, "SAP", "Software system", "On-prem business data and management")

Rel(user, spa, "Uses", "Equinor | AAD")
Rel(spa, api, "Requests", "user_impersonation")
Rel(api, db, "Reads/Writes")
Rel(api, db2, "Reads/Writes")
Rel(db, sap, "Reads/Writes", "Data sync")


SHOW_FLOATING_LEGEND()
Lay_Distance(LEGEND(), spa, 0)
@enduml